nome = input("Informe o seu nome: ")
print("Seja bem-vindo(a), Sr.", nome)
dia = input("Informe o dia do seu nascimento: ")
mes = input("Informe o mês do seu nascimento: ")
ano = input("Informe o ano do seu nascimento: ")
print("Você nasceu no dia", dia, "de", mes, "de", ano, ". Correto?")
